-- ═══════════════════════════════════════════════════════════════════════════════════
-- 024 — the decision record, and eleven decisions that already existed in the wrong place.
--
-- Every other human act in this system has an audit table. Approving has one. Reviewing has
-- one. Declaring a completion false has one. Handing a component to another machine has one,
-- and it refuses without a stated reason. DECIDING — the act the whole factory line exists to
-- serve — has had none, which is why `sandbox.system_change` sat at zero rows while eleven
-- `--sidebar-rail-*` tokens were proposed, approved, and authored into no file under
-- `tokens/`. A decision that is not recorded cannot be required, and cannot be reused.
--
-- ── This is a migration, not a schema design ───────────────────────────────────────
-- `proposedDarkRailTokens` in `sandbox/src/data/rail-sidebar.ts` already IS the precedent
-- table, written in the wrong place: eleven rows, each pairing an origin value with a chosen
-- value, under a proposed token name, with the usage it serves. It has been doing this table's
-- job in a TypeScript array that nothing can query, nothing can require, and no other
-- component can ever inherit from. The columns below are its shape, plus the two fields it
-- never had: who decided, and why.
--
-- Moving it also closes a gap the audit found in the corpus itself. Six of the nine B rows —
-- B-2, B-3, B-4, B-7, B-8, B-9 — carry `afterVar = null` and, in its place, the prose
-- `afterNote: "Resolved by Q2 and the approved Color token lab candidate."` That sentence is
-- an IOU pointing at a decision this database has never held. Their proposed token existed
-- only as `proposedVar` in the array, so the corpus could not answer "what token does B-2
-- propose" — which is exactly what a `token.authored` requirement (026) has to read. After
-- this migration every one of the nine has its token as a real column value, and the six are
-- promoted from `register = 'confirm'` to `'decide'`.
--
-- ── Nothing here was retyped, and no rationale was invented ────────────────────────
-- The values below were GENERATED by bundling the real module with esbuild and reading the
-- array — never transcribed by eye. CLAUDE.md checklist item 18 exists because a
-- fabricated-but-plausible value passes typecheck, build and smoke test and only fails under
-- close inspection against the real source.
--
-- `rationale` is NOT NULL and no row was given a manufactured one. Four tokens carry their own
-- `proposalNote`, written at the time the decision was revised — that IS the rationale, and it
-- is used verbatim. The other seven each have a B row whose `review_prompt` states the
-- constraint the value had to satisfy; that is used instead, and it is already covered against
-- drift by `db/verify-review-prompt-fidelity.mjs`. Every one of the eleven therefore carries a
-- real sentence somebody wrote about that specific value.
--
-- ── What is asserted rather than proven, said once, plainly ────────────────────────
-- `decided_by` is caller-supplied, exactly like `author_agent_id` and the machine name, and
-- for the same reason: all three machines share one `app_rw` principal, so the database cannot
-- prove who is on the other end. It is recorded as `owner` for all eleven, because the source
-- material attributes them to owner review sessions ("Q2 approved", "Approved: …") without
-- naming a person, and inventing one would be worse than the gap. `provenance` distinguishes
-- these reconstructed rows from anything recorded live afterwards, so no future reader has to
-- guess which is which. A named, timestamped, rationale-bearing record that is asserted is
-- still a very long way from zero.
--
-- ── disposition: all eleven are `authored`, and that is the finding ────────────────
-- Not one of the eleven resolves in `tokens/*.tokens.json` — verified by walking all three
-- token files and every nested group. Under the owner's own step 2 an authored value stays
-- blocked until the token exists, which is what 026 enforces. `reused` is the other half of
-- that rule and is not merely a placeholder: 13 further corpus rows propose tokens that DO
-- already resolve (`--accent`, `--border`, `--ring`, `--muted-foreground` and others), and
-- those are reuse decisions that belong in this table too. They are not seeded here because
-- this migration's contract is the array, and only the array — a wider sweep is a separate,
-- reviewable act.
-- ═══════════════════════════════════════════════════════════════════════════════════

CREATE TABLE sandbox.divergence_decision (
    decision_id       INT IDENTITY(1,1) PRIMARY KEY,
    component_id      INT           NOT NULL REFERENCES sandbox.component(component_id),
    -- Nullable on purpose: two of the eleven (`darkDividerSubtle`, `darkActiveHoverBg`) have
    -- no divergence row at all. They are real decisions with no row to hang from, which is
    -- itself worth being able to see — a decision table keyed strictly to divergences would
    -- have silently dropped them.
    divergence_id     INT           NULL     REFERENCES sandbox.divergence(divergence_id),
    concept           NVARCHAR(100) NOT NULL,
    usage_note        NVARCHAR(300) NULL,
    -- Origin's own value, and the value chosen instead. `_dark` is nullable because a decision
    -- that does not vary by mode has one value, not two; a colour in this project always has
    -- both, since the light/dark parity gate refuses anything else.
    origin_value      NVARCHAR(100) NULL,
    origin_value_dark NVARCHAR(100) NULL,
    chosen_value      NVARCHAR(100) NOT NULL,
    chosen_value_dark NVARCHAR(100) NULL,
    -- The token the decision lands in, when it lands in one. NULL for a decision about
    -- something other than a token (a structure, an element order, a behaviour).
    chosen_token      NVARCHAR(100) NULL,
    disposition       NVARCHAR(10)  NOT NULL
        CONSTRAINT ck_decision_disposition CHECK (disposition IN ('reused','authored')),
    rationale         NVARCHAR(MAX) NOT NULL
        CONSTRAINT ck_decision_rationale CHECK (LEN(LTRIM(RTRIM(rationale))) > 0),
    decided_by        NVARCHAR(100) NOT NULL,
    provenance        NVARCHAR(10)  NOT NULL
        CONSTRAINT ck_decision_provenance CHECK (provenance IN ('recorded','migrated')),
    decided_at        DATETIME2     NOT NULL CONSTRAINT df_decision_decided_at DEFAULT SYSUTCDATETIME(),
    created_at        DATETIME2     NOT NULL CONSTRAINT df_decision_created_at DEFAULT SYSUTCDATETIME()
);
GO

CREATE INDEX ix_decision_divergence ON sandbox.divergence_decision(divergence_id);
CREATE INDEX ix_decision_token      ON sandbox.divergence_decision(chosen_token);
GO

-- ── the eleven, generated from the real array ─────────────────────────────────────
DECLARE @component_id INT = (SELECT component_id FROM sandbox.component WHERE slug = 'rail-sidebar');

DECLARE @seed TABLE (
    ref_code    NVARCHAR(20)  NULL,
    concept     NVARCHAR(100) NOT NULL,
    token       NVARCHAR(100) NOT NULL,
    usage_note  NVARCHAR(300) NULL,
    origin_l    NVARCHAR(100) NULL,
    origin_d    NVARCHAR(100) NULL,
    chosen_l    NVARCHAR(100) NOT NULL,
    chosen_d    NVARCHAR(100) NULL,
    rationale   NVARCHAR(MAX) NOT NULL);

INSERT INTO @seed (ref_code, concept, token, usage_note, origin_l, origin_d, chosen_l, chosen_d, rationale)
VALUES
    (N'B-1', N'darkSurface', N'--sidebar-rail-surface', N'Rail background',
     N'#1c2024', N'#111113', N'oklch(0.205 0 0)', N'oklch(0.18 0 0)',
     N'Approved: oklch(0.18 0 0) for dark app mode only (light app mode''s oklch(0.205 0 0) is unchanged — no collision there against a white --background). Fixes the rail-matches-page-background problem while staying below darkHoverBg so hover still reads as an increase.'),
    (N'B-2', N'darkHoverBg', N'--sidebar-rail-hover', N'Row hover overlay',
     N'rgba(255,255,255,0.10)', N'#212225', N'oklch(0.301 0 0)', N'oklch(0.191 0 0)',
     N'What a rail row looks like on hover. Origin overlays white at 10%; bidezine has no equivalent, so this has to be a fixed colour rather than an overlay.'),
    (N'B-4', N'darkPressedBg', N'--sidebar-rail-pressed', N'Row pressed overlay',
     N'rgba(255,255,255,0.15)', N'#2e3135', N'oklch(0.348 0 0)', N'oklch(0.222 0 0)',
     N'What a rail row looks like while it is being pressed — the step between hover and active, and only visible for an instant.'),
    (N'B-3', N'darkActiveBg', N'--sidebar-rail-active', N'Row active/selected overlay',
     N'rgba(255,255,255,0.20)', N'#272a2d', N'oklch(0.39 0 0)', N'oklch(0.252 0 0)',
     N'What a rail row looks like when it is the current one. It has to read as clearly stronger than hover without competing with the icon on top of it.'),
    (N'B-5', N'darkBorderStrong', N'--sidebar-rail-border-strong', N'Visible border on the dark rail',
     N'rgba(255,255,255,0.6)', N'#5a6169', N'oklch(0.708 0 0)', N'oklch(0.708 0 0)',
     N'Approved: oklch(0.708 0 0) for both app modes (reuses the already-approved onDarkSubtle value / the base theme''s own --ring token) — visibly stronger against the rail surface than the original candidate.'),
    (NULL, N'darkDividerSubtle', N'--sidebar-rail-divider', N'Subtle horizontal divider between the rail''s logo/nav/footer groups',
     NULL, NULL, N'oklch(0.256 0 0)', N'oklch(0.254 0 0)',
     N'Reuses darkBorderStrong''s original, already-reviewed value (oklch(0.256)/oklch(0.254)), now under its own name so raising the ring''s brightness (M-13) doesn''t also brighten this divider.'),
    (N'B-6', N'onDark', N'--sidebar-rail-foreground', N'Full-strength text/icon on dark rail',
     N'#ffffff', N'#ffffff', N'oklch(0.985 0 0)', N'oklch(0.985 0 0)',
     N'Text and icons at full strength on the dark rail — the baseline the other three on-dark values step down from.'),
    (N'B-7', N'onDarkHover', N'--sidebar-rail-foreground-hover', N'≈85% on-dark, hover state',
     N'rgba(255,255,255,0.85)', N'#edeef0', N'oklch(0.922 0 0)', N'oklch(0.922 0 0)',
     N'Text and icons on a rail row being hovered. Origin lifts them to roughly 85%, which is a real step up from rest rather than a subtle one.'),
    (N'B-8', N'onDarkSubtle', N'--sidebar-rail-foreground-subtle', N'≈50% on-dark, subordinate text',
     N'rgba(255,255,255,0.5)', N'#696e77', N'oklch(0.708 0 0)', N'oklch(0.708 0 0)',
     N'Subordinate text on the rail, around 50% strength. Note it carries two roles: the browsing ring reuses this same value, so a change here moves both.'),
    (N'B-9', N'onDarkDisabled', N'--sidebar-rail-foreground-disabled', N'≈20% on-dark, disabled',
     N'rgba(255,255,255,0.2)', N'#3e4348', N'oklch(0.42 0 0)', N'oklch(0.375 0 0)',
     N'Disabled text and icons on the rail, around 20%. It has to stay legible enough to read as disabled text rather than as a rendering artefact.'),
    (NULL, N'darkActiveHoverBg', N'--sidebar-rail-active-hover', N'Select-hover overlay — the ALREADY-selected row, additionally hovered',
     NULL, NULL, N'oklch(0.43 0 0)', N'oklch(0.282 0 0)',
     N'Approved — extends the already-approved hover→pressed→active ramp one more step, inspired by navigation-menu.tsx''s own data-[active=true]:hover:bg-accent precedent.');

INSERT INTO sandbox.divergence_decision
    (component_id, divergence_id, concept, usage_note,
     origin_value, origin_value_dark, chosen_value, chosen_value_dark,
     chosen_token, disposition, rationale, decided_by, provenance)
SELECT  @component_id,
        d.divergence_id,
        s.concept,
        s.usage_note,
        s.origin_l,
        s.origin_d,
        s.chosen_l,
        s.chosen_d,
        s.token,
        -- Every one of the eleven: none resolves in tokens/ today.
        'authored',
        s.rationale,
        'owner',
        'migrated'
FROM    @seed s
LEFT JOIN sandbox.divergence d
       ON d.component_id = @component_id AND d.ref_code = s.ref_code;
GO

-- ── the six rows the register backfill could not see ──────────────────────────────
-- 023 registered a row `decide` when its own `visual` named an after-value. These six name
-- none — the prose IOU sits where the value should be — so they were left `confirm`, which is
-- the register that asks only for evidence and a review. They are decisions, and now there is
-- a row proving it: promote exactly the rows this migration just gave a decision to.
UPDATE  d
SET     d.register   = 'decide',
        d.updated_at = SYSUTCDATETIME()
FROM    sandbox.divergence d
WHERE   d.register = 'confirm'
  AND   EXISTS (SELECT 1 FROM sandbox.divergence_decision dd WHERE dd.divergence_id = d.divergence_id);
GO

-- ── append-only ───────────────────────────────────────────────────────────────────
-- Writes go through `usp_record_decision` (025) and nowhere else, which is how `evidence` and
-- `review` are already protected (019). The DENY is what makes the procedure the only door:
-- an unbroken ownership chain lets the procedure insert on the caller's behalf, while a direct
-- INSERT from `app_rw` is refused — so the mandatory rationale and the ownership check cannot
-- be walked around by writing to the table instead.
GRANT SELECT ON OBJECT::sandbox.divergence_decision TO app_rw;
GRANT SELECT ON OBJECT::sandbox.divergence_decision TO agent_rw;
GRANT SELECT ON OBJECT::sandbox.divergence_decision TO runner_evidence;
DENY  INSERT, UPDATE, DELETE ON OBJECT::sandbox.divergence_decision TO app_rw;
DENY  INSERT, UPDATE, DELETE ON OBJECT::sandbox.divergence_decision TO agent_rw;
DENY  INSERT, UPDATE, DELETE ON OBJECT::sandbox.divergence_decision TO runner_evidence;
GO
