-- ═══════════════════════════════════════════════════════════════════════════════════
-- 029 — the register is what the reviewer is ASKED TO DO, not whether a value was proposed.
--
-- 023's backfill was wrong on 100 of 169 rows, and wrong in the way that matters most: it
-- disagreed about the DECIDE set, which is the owner's actual queue. Caught by wiring the card
-- to the stored column and measuring the result before shipping it.
--
--     close   -> confirm   61     `close` did not exist in the column at all
--     confirm -> decide    26
--     decide  -> confirm   11     every row the owner is currently working from
--     decide  -> close      2
--
-- Not one of the 21 rows 023 marked `decide` is `decide` by its own prompt, and it found none
-- of the 11 that are. Had the card trusted the column, the decision queue would have silently
-- become 28 different rows. 61 rows carrying the literal sentence "Found and fixed during
-- build. Nothing to decide — this needs a measurement and an independent review before it can
-- close" were stored as `confirm`. §3.10 defines three registers; the column held two.
--
-- ── The cause, stated plainly, because it generalises ──────────────────────────────
-- 023 classified by WHETHER A VALUE WAS PROPOSED — a structural signal, chosen because it was
-- mechanical and available. The register is about WHAT A HUMAN IS ASKED FOR. Most colour rows
-- do both: they propose a value AND are already settled, needing only measurement and review.
-- The two questions are independent, and a proxy for one is not evidence about the other.
--
-- 023's own header argued that `close` should stay empty because "nobody needs to look at this
-- is not a judgement a backfill can make". That was written while 61 rows said so in a fixed
-- literal sentence, unread. The lesson is not "read harder": it is that the 169 descriptions
-- were ALREADY authored in §3.10's vocabulary, and the backfill invented a second one instead
-- of reading the first.
--
-- ── The CHECK is dropped, not adjusted ────────────────────────────────────────────
-- `ck_divergence_register_proposal` said a row whose `visual` proposes an after-value cannot be
-- registered `confirm`. Against the correct data it refuses all 21 such rows — 19 `confirm`,
-- 2 `close` — so it is not a strict-enough invariant that needs loosening; the invariant does
-- not exist. A row can legitimately propose a value and be past the point of deciding it.
--
-- What replaces it is not another constraint but a CHECK OF THE CONVENTION ITSELF:
-- `scripts/check-register.mjs` asserts every prompt-derived row's stored register still equals
-- what `sandbox/src/lib/register.ts` derives, importing that module rather than restating it.
-- A convention nothing verifies is what put the column and the prose out of step.
--
-- ── register_source, and the one row that deviates on purpose ──────────────────────
-- F-1 was reopened today against `decision.present` and re-registered `decide` by explicit
-- instruction, because its justification for 54px was "that's what origin used". Its PROMPT
-- still reads "Confirm the wider rail is right" — it was written before the reopen — so a
-- blanket backfill would silently revert a deliberate act. That is exactly the failure this
-- migration is fixing, and reproducing it in the fix would be worse than the original.
--
-- So `register_source` records whether a row's register came from its prompt or from a human
-- saying otherwise. The drift check only holds `prompt` rows to the convention, which means
-- F-1 is exempt VISIBLY rather than through an exception list in code. 023's
-- `usp_set_register` already demanded a reason and then discarded it; it now marks the row
-- `explicit` so the deviation is a fact in the table.
--
-- F-1's prompt should be rewritten to read as a decision. That belongs to whoever owns the
-- card's descriptions, and until it happens F-1 is the one row where stored and derived
-- disagree — by design, and recorded.
-- ═══════════════════════════════════════════════════════════════════════════════════

ALTER TABLE sandbox.divergence DROP CONSTRAINT ck_divergence_register_proposal;
GO

ALTER TABLE sandbox.divergence
    ADD register_source NVARCHAR(10) NOT NULL
        CONSTRAINT df_divergence_register_source DEFAULT 'prompt';
GO

ALTER TABLE sandbox.divergence
    ADD CONSTRAINT ck_divergence_register_source
        CHECK (register_source IN ('prompt','explicit'));
GO

-- Generated by running sandbox/src/lib/register.ts's own `registerOf` over every row, with no
-- `register` key passed so it could not short-circuit on the column it is replacing. Never
-- re-implemented here: re-implementing that rule is what produced the bug above.
UPDATE d SET d.register = 'decide', d.register_source = 'prompt', d.updated_at = SYSUTCDATETIME()
FROM   sandbox.divergence d JOIN sandbox.component c ON c.component_id = d.component_id
WHERE  c.slug = 'rail-sidebar'
  AND  d.ref_code IN ('G-1', 'H-2', 'H-3', 'H-4', 'H-5', 'H-6', 'R-11', 'R-5', 'R-6', 'R-8', 'R-9');
GO

UPDATE d SET d.register = 'confirm', d.register_source = 'prompt', d.updated_at = SYSUTCDATETIME()
FROM   sandbox.divergence d JOIN sandbox.component c ON c.component_id = d.component_id
WHERE  c.slug = 'rail-sidebar'
  AND  d.ref_code IN ('A-1', 'A-2', 'A-3', 'A-4', 'A-5', 'A-6', 'A-7', 'A-8', 'A-9', 'B-1', 'B-2', 'B-3', 'B-4',
           'B-5', 'B-6', 'B-7', 'B-8', 'B-9', 'C-1', 'C-10', 'C-11', 'C-12', 'C-13', 'C-14', 'C-2',
           'C-3', 'C-4', 'C-5', 'C-6', 'C-7', 'C-8', 'C-9', 'D-1', 'D-10', 'D-12', 'D-2', 'D-3', 'D-4',
           'D-5', 'D-6', 'D-7', 'D-8', 'D-9', 'E-1', 'E-2', 'E-3', 'E-4', 'E-5', 'E-6', 'E-7', 'F-1',
           'F-10', 'F-11', 'F-2', 'F-3', 'F-4', 'F-5', 'F-6', 'F-7', 'F-8', 'F-9', 'G-2', 'G-3', 'G-4',
           'H-1', 'H-7', 'H-8', 'I-1', 'J-1', 'J-2', 'K-1', 'K-2', 'K-3', 'K-4', 'L-1', 'M-1', 'M-10',
           'M-2', 'M-3', 'M-4', 'M-5', 'M-6', 'M-7', 'M-8', 'M-9', 'Q1', 'Q2', 'Q3', 'Q4', 'R-1', 'R-10',
           'R-2', 'R-3', 'R-4', 'R-7');
GO

UPDATE d SET d.register = 'close', d.register_source = 'prompt', d.updated_at = SYSUTCDATETIME()
FROM   sandbox.divergence d JOIN sandbox.component c ON c.component_id = d.component_id
WHERE  c.slug = 'rail-sidebar'
  AND  d.ref_code IN ('D-11', 'L-10', 'L-11', 'L-12', 'L-13', 'L-14', 'L-15', 'L-16', 'L-17', 'L-18', 'L-19', 'L-2',
           'L-20', 'L-21', 'L-22', 'L-23', 'L-24', 'L-25', 'L-26', 'L-27', 'L-28', 'L-29', 'L-3', 'L-30',
           'L-31', 'L-32', 'L-33', 'L-34', 'L-35', 'L-36', 'L-37', 'L-38', 'L-39', 'L-4', 'L-40', 'L-41',
           'L-42', 'L-43', 'L-44', 'L-45', 'L-46', 'L-47', 'L-48', 'L-49', 'L-5', 'L-50', 'L-51', 'L-6',
           'L-7', 'L-8', 'L-9', 'M-11', 'M-12', 'M-13', 'M-14', 'M-15', 'M-16', 'M-17', 'M-18', 'M-19',
           'M-20', 'M-21', 'M-22');
GO
-- F-1, restored to the register a human set and marked as such. Runs AFTER the backfill on
-- purpose: the backfill legitimately claims every prompt-derived row, and this states the
-- exception rather than carving a hole in the rule.
UPDATE d
SET    d.register        = 'decide',
       d.register_source = 'explicit',
       d.updated_at      = SYSUTCDATETIME()
FROM   sandbox.divergence d JOIN sandbox.component c ON c.component_id = d.component_id
WHERE  c.slug = 'rail-sidebar' AND d.ref_code = 'F-1';
GO

CREATE OR ALTER PROCEDURE sandbox.usp_set_register
    @divergence_id INT,
    @register      NVARCHAR(10),
    @machine       NVARCHAR(50),
    @reason        NVARCHAR(400)
AS
BEGIN
    SET NOCOUNT ON;

    IF @register NOT IN ('decide','confirm','close')
        THROW 51010, 'register must be decide, confirm or close.', 1;

    IF @reason IS NULL OR LEN(LTRIM(RTRIM(@reason))) = 0
        THROW 51011, 'A reason is required: re-registering a row changes what a human is asked to do with it.', 1;

    DECLARE @component_id INT =
        (SELECT component_id FROM sandbox.divergence WHERE divergence_id = @divergence_id);
    IF @component_id IS NULL THROW 51013, 'No such divergence.', 1;

    -- Table-valued, not scalar: TOP 1 so the caller sees the refusal that actually applies
    -- rather than a concatenation of every reason it might have been refused.
    DECLARE @refusal NVARCHAR(400) =
        (SELECT TOP 1 reason FROM sandbox.fn_component_write_refusal(@component_id, @machine));
    IF @refusal IS NOT NULL THROW 51012, @refusal, 1;

    -- 029: mark the row as humanly set, so the prompt-derived backfill and the drift check
    -- both leave it alone. Without this a later backfill silently reverts a deliberate act,
    -- which is the failure 029 exists to fix.
    UPDATE sandbox.divergence
    SET    register        = @register,
           register_source = 'explicit',
           updated_at      = SYSUTCDATETIME()
    WHERE  divergence_id = @divergence_id;
END
GO
