// Build the browser-only UMD bundle → dist-browser/ds.umd.js (window.DS) + ds-manifest.json.
// Stamps window.DS.version = <pkg version>+<git sha> and records the source hash so a copied bundle's
// staleness is detectable (scripts/check-umd-fresh.mjs). See src/umd-entry.ts / vite.umd.config.ts.
import fs from "node:fs";
import path from "node:path";
import { execSync } from "node:child_process";
import { ROOT, sourceHash } from "./lib/umd-source-hash.mjs";

const pkg = JSON.parse(fs.readFileSync(path.join(ROOT, "package.json"), "utf-8"));
let sha = "nogit";
try { sha = execSync("git rev-parse --short HEAD", { cwd: ROOT }).toString().trim(); } catch { /* no git */ }
const version = `${pkg.version}+${sha}`;

console.log(`[build:umd] building ds.umd.js  version=${version}`);
execSync("npx vite build --config vite.umd.config.ts", {
  cwd: ROOT,
  stdio: "inherit",
  env: { ...process.env, DS_BUILD_VERSION: version },
});

const outDir = path.join(ROOT, "dist-browser");
const bundlePath = path.join(outDir, "ds.umd.js");
if (!fs.existsSync(bundlePath)) {
  console.error("[build:umd] FAILED — dist-browser/ds.umd.js was not produced");
  process.exit(1);
}
const bytes = fs.statSync(bundlePath).size;

const manifest = {
  name: "@miguel/design-system browser UMD bundle",
  global: "DS",
  version,
  packageVersion: pkg.version,
  gitSha: sha,
  sourceHash: sourceHash(),
  externals: { react: "window.React", "react-dom": "window.ReactDOM", recharts: "excluded (chart-free core)" },
  reactTarget: "18.3.1 UMD (classic createElement via jsx-runtime shim); also runs on React 19",
  bytes,
  note: "Generated by scripts/build-umd.mjs — do not hand-edit. Regenerate with `npm run build:umd`.",
};
fs.writeFileSync(path.join(outDir, "ds-manifest.json"), JSON.stringify(manifest, null, 2) + "\n");
console.log(`[build:umd] wrote dist-browser/ds.umd.js (${(bytes / 1024).toFixed(0)} KB) + ds-manifest.json`);

// Consumer-facing prop/type reference for browser consumers (finding CD1.3). Regenerated here so it can
// never drift from the bundle; its freshness is covered by the same sourceHash gate (check:umd-fresh).
execSync("node scripts/gen-umd-api.mjs", { cwd: ROOT, stdio: "inherit" });
