#!/usr/bin/env node
/**
 * Fluent UI System Icons (regular + optional filled, 20px)  -> generated React icon components.
 *
 * Reads   icons/manifest.json                     (name -> Fluent slug, or custom path data)
 * Writes  src/icons/generated.tsx                 (one React component per entry)
 *
 * The output is GENERATED. Never hand-edit it, and never import an icon package
 * (lucide-react or otherwise) directly anywhere in src/ or site/src/ — add the
 * mapping here, in the manifest, so every icon in the system is traceable to one
 * source of truth. Mirrors scripts/build-tokens.mjs's tokens/*.tokens.json pattern.
 *
 * Fails loudly (non-zero exit) if a manifest entry names a Fluent slug that isn't
 * actually installed in node_modules/@fluentui/svg-icons — the icon equivalent of
 * the token light/dark parity gate.
 */

import { readFileSync, writeFileSync, mkdirSync, existsSync } from "node:fs"
import { fileURLToPath } from "node:url"
import { dirname, join } from "node:path"

const root = join(dirname(fileURLToPath(import.meta.url)), "..")
const manifest = JSON.parse(
  readFileSync(join(root, "icons", "manifest.json"), "utf8")
)
const fluentIconsDir = join(root, "node_modules", "@fluentui", "svg-icons", "icons")

const entries = Object.entries(manifest).filter(([key]) => !key.startsWith("$"))

/** Extract the inner markup (paths/groups) and viewBox out of a Fluent .svg file. */
function readFluentIcon(name, slug) {
  const file = join(fluentIconsDir, `${slug}.svg`)
  if (!existsSync(file)) {
    throw new Error(
      `Icon "${name}": manifest names Fluent slug "${slug}", but ` +
        `node_modules/@fluentui/svg-icons/icons/${slug}.svg does not exist. ` +
        `Run "npm install" or fix icons/manifest.json.`
    )
  }
  const svg = readFileSync(file, "utf8")
  const viewBoxMatch = svg.match(/viewBox="([^"]+)"/)
  const innerMatch = svg.match(/<svg[^>]*>([\s\S]*)<\/svg>/)
  if (!viewBoxMatch || !innerMatch) {
    throw new Error(`Icon "${name}": could not parse ${slug}.svg — unexpected SVG shape.`)
  }
  return { viewBox: viewBoxMatch[1], inner: innerMatch[1] }
}

function readOptionalFluentIcon(slug) {
  const file = join(fluentIconsDir, `${slug}.svg`)
  if (!existsSync(file)) return null
  const svg = readFileSync(file, "utf8")
  const viewBoxMatch = svg.match(/viewBox="([^"]+)"/)
  const innerMatch = svg.match(/<svg[^>]*>([\s\S]*)<\/svg>/)
  if (!viewBoxMatch || !innerMatch) {
    throw new Error(`Could not parse ${slug}.svg — unexpected SVG shape.`)
  }
  return { viewBox: viewBoxMatch[1], inner: innerMatch[1] }
}

function filledSlugFor(def) {
  if (def.filled) return def.filled
  if (typeof def.fluent === "string" && def.fluent.endsWith("_regular")) {
    return def.fluent.replace(/_regular$/, "_filled")
  }
  return null
}

/** Render one entry (stock Fluent slug or custom inline path data) as a component. */
function renderComponent(name, def) {
  const { viewBox, inner } = def.custom
    ? { viewBox: def.viewBox, inner: def.path }
    : readFluentIcon(name, def.fluent)
  const filledSlug = def.custom ? null : filledSlugFor(def)
  const filledIcon = filledSlug ? readOptionalFluentIcon(filledSlug) : null

  if (def.custom && !def.viewBox) {
    throw new Error(`Icon "${name}": custom entries must set "viewBox".`)
  }

  return `export function ${name}({ filled = false, ...props }: React.SVGProps<SVGSVGElement> & { filled?: boolean }) {
  return (
    <svg
      xmlns="http://www.w3.org/2000/svg"
      viewBox={filled ? "${filledIcon?.viewBox ?? viewBox}" : "${viewBox}"}
      fill="currentColor"
      aria-hidden="true"
      {...props}
    >
      {filled ? (
        <>
          ${filledIcon?.inner ?? inner}
        </>
      ) : (
        <>
          ${inner}
        </>
      )}
    </svg>
  )
}
`
}

const componentsSrc = entries
  .map(([name, def]) => renderComponent(name, def))
  .join("\n")

const banner = `/* GENERATED by scripts/build-icons.mjs from icons/manifest.json — DO NOT EDIT. */`

const tsx = `${banner}
/* eslint-disable */
import type * as React from "react"

${componentsSrc}`

mkdirSync(join(root, "src", "icons"), { recursive: true })
writeFileSync(join(root, "src", "icons", "generated.tsx"), tsx)

console.log(
  `icons: ${entries.length} emitted → src/icons/generated.tsx (${entries.filter(([, d]) => d.custom).length} custom, ${entries.filter(([, d]) => !d.custom).length} stock Fluent)`
)
