#!/usr/bin/env node
/**
 * DTCG token source  →  CSS custom properties + typed tokens.
 *
 * Reads   tokens/{base,light,dark}.tokens.json   (DTCG 2025.10 — ADR-001)
 * Writes  src/styles/tokens.css                  (runtime: :root + .dark)
 *         src/tokens.ts                          (authoring: typed names + var() refs)
 *
 * Both outputs are GENERATED. Never hand-edit them, and never add a CSS variable
 * directly to a stylesheet — add it here, in the DTCG source, so the typed surface
 * and the runtime surface can never drift apart. (ADR-006, Step 2.)
 */

import { readFileSync, writeFileSync, mkdirSync } from "node:fs"
import { fileURLToPath } from "node:url"
import { dirname, join } from "node:path"

const root = join(dirname(fileURLToPath(import.meta.url)), "..")
const read = (name) =>
  JSON.parse(readFileSync(join(root, "tokens", `${name}.tokens.json`), "utf8"))

/** Strip DTCG metadata keys ($description etc.) to leave just the tokens. */
const entries = (doc) =>
  Object.entries(doc).filter(([key]) => !key.startsWith("$"))

/** Render one DTCG $value as a CSS value. */
function toCss(token, name) {
  const { $type: type, $value: value } = token

  switch (type) {
    case "color": {
      if (typeof value === "string") return value // hex passthrough
      const { colorSpace, components, alpha } = value
      if (colorSpace !== "oklch") {
        throw new Error(`Token "${name}": unsupported colorSpace "${colorSpace}".`)
      }
      const channels = components.join(" ")
      return alpha === undefined || alpha === 1
        ? `oklch(${channels})`
        : `oklch(${channels} / ${alpha})`
    }
    case "dimension":
      return `${value.value}${value.unit}`
    case "fontFamily":
      return (Array.isArray(value) ? value : [value])
        .map((f) => (f.includes(" ") ? `"${f}"` : f))
        .join(", ")
    default:
      throw new Error(`Token "${name}": unsupported $type "${type}".`)
  }
}

const block = (doc) =>
  entries(doc)
    .map(([name, token]) => `  --${name}: ${toCss(token, name)};`)
    .join("\n")

const base = read("base")
const light = read("light")
const dark = read("dark")

// ── Parity gate ────────────────────────────────────────────────────────────
// A token that exists in one mode but not the other renders as "unset" there,
// silently falling back to an inherited value. Fail the build instead.
const lightNames = entries(light).map(([n]) => n)
const darkNames = entries(dark).map(([n]) => n)
const missingInDark = lightNames.filter((n) => !darkNames.includes(n))
const missingInLight = darkNames.filter((n) => !lightNames.includes(n))

if (missingInDark.length || missingInLight.length) {
  const lines = [
    "Token parity check FAILED — light and dark must declare the same names.",
    ...missingInDark.map((n) => `  missing in dark.tokens.json:  ${n}`),
    ...missingInLight.map((n) => `  missing in light.tokens.json: ${n}`),
  ]
  console.error(lines.join("\n"))
  process.exit(1)
}

// ── Emit CSS ───────────────────────────────────────────────────────────────
const banner = `/* GENERATED by scripts/build-tokens.mjs from tokens/*.tokens.json — DO NOT EDIT. */`

const css = `${banner}

:root {
${block(base)}
${block(light)}
}

.dark {
${block(dark)}
}
`

// ── Emit typed tokens ──────────────────────────────────────────────────────
const allNames = [...entries(base).map(([n]) => n), ...lightNames]

const ts = `${banner}

/** Every design token this system exposes as a CSS custom property. */
export const tokenNames = [
${allNames.map((n) => `  "${n}",`).join("\n")}
] as const

export type TokenName = (typeof tokenNames)[number]

/**
 * Typed \`var()\` references, for the rare place a token is needed from TS
 * (inline styles, canvas, chart libraries) rather than a Tailwind utility.
 */
export const token: Record<TokenName, string> = {
${allNames.map((n) => `  "${n}": "var(--${n})",`).join("\n")}
}
`

mkdirSync(join(root, "src", "styles"), { recursive: true })
writeFileSync(join(root, "src", "styles", "tokens.css"), css)
writeFileSync(join(root, "src", "tokens.ts"), ts)

console.log(
  `tokens: ${allNames.length} emitted → src/styles/tokens.css, src/tokens.ts (light/dark parity OK)`
)
