import { useEffect, useState } from "react"
import { MoonIcon, SunIcon } from "lucide-react"
import {
  Button,
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
  themeNames,
  type ThemeName,
} from "@bidezine/system"

type Mode = "light" | "dark"
type Preset = "default" | ThemeName

const MODE_KEY = "bidezine-mode"
const PRESET_KEY = "bidezine-preset"

function readMode(): Mode {
  if (typeof window === "undefined") return "light"
  const stored = window.localStorage.getItem(MODE_KEY)
  if (stored === "light" || stored === "dark") return stored
  return window.matchMedia("(prefers-color-scheme: dark)").matches ? "dark" : "light"
}

function readPreset(): Preset {
  if (typeof window === "undefined") return "default"
  const stored = window.localStorage.getItem(PRESET_KEY)
  if (stored === "default" || themeNames.includes(stored as ThemeName)) {
    return stored as Preset
  }
  return "default"
}

/**
 * Applies mode (light/dark) via the `.dark` class and the preset via
 * `data-theme`, exactly matching the selector shapes generated by
 * scripts/build-tokens.mjs into src/styles/tokens.css.
 */
function applyTheme(mode: Mode, preset: Preset) {
  const root = document.documentElement
  root.classList.toggle("dark", mode === "dark")
  if (preset === "default") {
    delete root.dataset.theme
  } else {
    root.dataset.theme = preset
  }
}

const presetLabels: Record<string, string> = {
  default: "Default",
  daylight: "Daylight",
  emerald: "Emerald",
  midnight: "Midnight",
}

export function ThemeSwitcher() {
  const [mode, setMode] = useState<Mode>(readMode)
  const [preset, setPreset] = useState<Preset>(readPreset)

  useEffect(() => {
    applyTheme(mode, preset)
    window.localStorage.setItem(MODE_KEY, mode)
    window.localStorage.setItem(PRESET_KEY, preset)
  }, [mode, preset])

  return (
    <div className="flex items-center gap-2">
      <Select value={preset} onValueChange={(value) => setPreset(value as Preset)}>
        <SelectTrigger size="sm" aria-label="Theme preset" className="flex-1">
          <SelectValue />
        </SelectTrigger>
        <SelectContent>
          <SelectItem value="default">{presetLabels.default}</SelectItem>
          {themeNames.map((name) => (
            <SelectItem key={name} value={name}>
              {presetLabels[name] ?? name}
            </SelectItem>
          ))}
        </SelectContent>
      </Select>
      <Button
        variant="outline"
        size="icon-sm"
        aria-label={mode === "dark" ? "Switch to light mode" : "Switch to dark mode"}
        onClick={() => setMode(mode === "dark" ? "light" : "dark")}
      >
        {mode === "dark" ? <MoonIcon /> : <SunIcon />}
      </Button>
    </div>
  )
}
