import { useEffect, useState } from "react"
import { Moon, Sun } from "lucide-react"
import { themeNames, type ThemeName } from "@bidezine/system"

type Mode = "light" | "dark"
type Preset = "default" | ThemeName

const MODE_KEY = "bidezine-mode"
const PRESET_KEY = "bidezine-preset"

function readMode(): Mode {
  if (typeof window === "undefined") return "light"
  const stored = window.localStorage.getItem(MODE_KEY)
  if (stored === "light" || stored === "dark") return stored
  return window.matchMedia("(prefers-color-scheme: dark)").matches
    ? "dark"
    : "light"
}

function readPreset(): Preset {
  if (typeof window === "undefined") return "default"
  const stored = window.localStorage.getItem(PRESET_KEY)
  if (stored === "default" || themeNames.includes(stored as ThemeName)) {
    return stored as Preset
  }
  return "default"
}

/**
 * Applies mode (light/dark) via the `.dark` class and the preset via
 * `data-theme`, exactly matching the selector shapes generated by
 * scripts/build-tokens.mjs into src/styles/tokens.css.
 */
function applyTheme(mode: Mode, preset: Preset) {
  const root = document.documentElement
  root.classList.toggle("dark", mode === "dark")
  if (preset === "default") {
    delete root.dataset.theme
  } else {
    root.dataset.theme = preset
  }
}

const presetLabels: Record<Preset, string> = {
  default: "Default",
  daylight: "Daylight",
  emerald: "Emerald",
  midnight: "Midnight",
}

export function ThemeSwitcher() {
  const [mode, setMode] = useState<Mode>(readMode)
  const [preset, setPreset] = useState<Preset>(readPreset)

  useEffect(() => {
    applyTheme(mode, preset)
    window.localStorage.setItem(MODE_KEY, mode)
    window.localStorage.setItem(PRESET_KEY, preset)
  }, [mode, preset])

  return (
    <div className="flex items-center gap-2">
      <select
        aria-label="Theme preset"
        value={preset}
        onChange={(e) => setPreset(e.target.value as Preset)}
        className="flex-1 rounded-md border border-border bg-background px-2 py-1 text-xs text-foreground"
      >
        <option value="default">{presetLabels.default}</option>
        {themeNames.map((name) => (
          <option key={name} value={name}>
            {presetLabels[name] ?? name}
          </option>
        ))}
      </select>
      <button
        type="button"
        aria-label={mode === "dark" ? "Switch to light mode" : "Switch to dark mode"}
        onClick={() => setMode((m) => (m === "dark" ? "light" : "dark"))}
        className="flex size-7 shrink-0 items-center justify-center rounded-md border border-border bg-background text-foreground hover:bg-accent"
      >
        {mode === "dark" ? (
          <Moon className="size-3.5" />
        ) : (
          <Sun className="size-3.5" />
        )}
      </button>
    </div>
  )
}
